# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKLycsWTZ3zNfaG3FOidEPlj3_WM64j1
"""

import streamlit as st
import tensorflow as tf

@st.cache_data(allow_output_mutation=True)
def load_model():
  model=tf.keras.models.load_model('cats_and_dogs_small_4.h5')
  return model
model=load_model()
st.write("""
# Dog vs Cat Classification"""
)
file=st.file_uploader("Choose a photo from computer",type=["jpg","png"])

import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(64,64)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['Dog', 'Cat']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)
